### PR TITLE
Fix MA0006/MA0154 analyzer violations introduced in #5570

### PR DESCRIPTION
**Pull request by sdanyliv**
## Problem

`master` (tip `1ae9418`, from #5570 merged 2026-06-07) does not build in Release.
A plain `dotnet build Source/LinqToDB/LinqToDB.csproj -c Release` fails with four
analyzer errors:

```
Source/LinqToDB/Internal/SqlProvider/SqlExpressionOptimizerVisitor.cs(1407,9): error MA0006
Source/LinqToDB/Internal/SqlQuery/QueryHelper.cs(1674,15): error MA0154
Source/LinqToDB/Internal/SqlQuery/QueryHelper.cs(1681,15): error MA0154
Source/LinqToDB/Internal/SqlQuery/QueryHelper.cs(1702,14): error MA0006
```

#5570's new case-conversion folding code compares strings with `==` and uses
`<c>true</c>` in XML doc comments. Under this repo's analyzer config these are
**errors** for `Source/` code (`dotnet_analyzer_diagnostic.severity = error`, and
`dotnet_diagnostic.MA0154.severity = error`). The `dotnet_diagnostic.MA0006.severity = none`
override only applies under `[Tests/**]`, so it does not cover production code.

## Fix

- `string.Equals(x, y, StringComparison.Ordinal)` for the two function-name
  comparisons — behaviour-identical, since `==` on `string` already does ordinal
  comparison.
- `<see langword="true"/>` instead of `<c>true</c>` in the two XML doc comments.

No functional change. `dotnet build Source/LinqToDB/LinqToDB.csproj -c Release` is
green after the fix.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by MaceWindu** [comment]
## 📝 Release-notes draft

<sub>🤖 Auto-generated user-facing summary for this PR. Toggle the boxes to control how it ships; the text is regenerated when new commits land (the maintainer confirms every change).</sub>

- [x] **Omit from release notes** (exclude from both the wiki notes and the GitHub release highlights)
- [ ] **Include in the GitHub release highlights** (the brief release-page notes)

### Full release notes (wiki)

_(none — nothing user-facing in this PR)_


### GitHub release highlight (brief)

_(none)_


---
<sub>Generated from commit `41aaf5f`.</sub>
