### ISSUE TITLE
Regression in .NET SDK 10.0.201: Query with window function and CTE fails in F# but works in C#.

### ISSUE THREAD

**Issue by gubser** [linq2db/linq2db#5428]
### Description

In F#, the following query works in 10.0.103 but fails in .NET SDK 10.0.201.
I translated into C# as well and there it works for both 10.0.103 and 10.0.201. I don't know where to start digging, maybe they've changed how F# compiler translates functions into linq expressions.

```fsharp
[<Test>]
let TestWindow () =
    use conn  = new MyDataConnection(dataOptions)

    let table = conn.CreateTempTable<Template>("my_entities", [
        { TemplateId = 1; ParentId = 1; ValidFrom = LocalDate(2026, 3, 15) }
        { TemplateId = 2; ParentId = 1;ValidFrom = LocalDate(2026, 3, 16) }
        { TemplateId = 3; ParentId = 1;ValidFrom = LocalDate(2026, 4, 17) }
    ])

    let dateInterval = DateInterval(LocalDate(2026, 3, 1), LocalDate(2026, 3, 31))

    let cte = 
        table.Select(fun d -> {|
            ValidUntilExcludingEnd =
                Sql.Ext
                    .Lead<Nullable<LocalDate>>(d.ValidFrom)
                    .Over()
                    .PartitionBy(d.ParentId)
                    .OrderBy(d.ValidFrom)
                    .ToValue()

            Template = d
        |})
        |> _.AsCte("templates_with_valid_until")

    let count =
        cte
        |> _.Where(fun d -> Sql.Parameter(dateInterval).Contains(d.Template.ValidFrom))
        |> _.Count()

    Assert.That(count, Is.EqualTo(2))
```

Notably, this simpler query without window function and CTE works fine:

```fsharp
[<Test>]
let TestSimple () =
    use conn  = new MyDataConnection(dataOptions)

    let table = conn.CreateTempTable<Template>("my_entities", [
        { TemplateId = 1; ParentId = 1; ValidFrom = LocalDate(2026, 3, 15) }
        { TemplateId = 2; ParentId = 1;ValidFrom = LocalDate(2026, 3, 16) }
        { TemplateId = 3; ParentId = 1;ValidFrom = LocalDate(2026, 4, 17) }
    ])

    let dateInterval = DateInterval(LocalDate(2026, 3, 1), LocalDate(2026, 3, 31))

    let q2 =
        table
        |> _.Where(fun d -> Sql.Parameter(dateInterval).Contains(d.ValidFrom))
        |> _.Count()

    Assert.That(q2, Is.EqualTo(2))
```

You can find both tests in provided test repositories.

### Reproduction Steps

I've set up an F# and a C# repo to narrow down this issue.

F# (works fine in 10.0.103 but fails in 10.0.201):

1. Clone https://github.com/gubser/linq2db-window-query
2. Run `docker compose run --build --rm test-201` to see it fail.
3. Run `docker compose run --build --rm test-103` to see it succeed.

C# (works fine in both 10.0.103 and 10.0.201):

1. Clone https://github.com/gubser/linq2db-window-query-csharp
2. Run `docker compose run --build --rm test-201` to see it succeed.
3. Run `docker compose run --build --rm test-103` to see it succeed.

### Exception details

```
Restore complete (0.5s)
  LinqToDbQueryTests net10.0 succeeded (2.4s) → bin/Debug/net10.0/LinqToDbQueryTests.dll
NUnit Adapter 5.0.0.0: Test execution started
Running all tests in /src/bin/Debug/net10.0/LinqToDbQueryTests.dll
   NUnit3TestExecutor discovered 2 of 2 NUnit test cases using Current Discovery mode, Non-Explicit run
NUnit Adapter 5.0.0.0: Test execution complete
  LinqToDbQueryTests test net10.0 failed with 1 error(s) (1.8s)
    /_/Source/LinqToDB/Internal/Linq/Builder/ExpressionBuilder.cs(376): error TESTERROR: 
      TestWindow (88ms): Error Message: LinqToDB.LinqToDBException : The LINQ expression could not be converted to SQL.
      Expression:
      LinqToDbQuery10_0_201.dateIntervalContains(
      	d: Sql.Parameter<DateInterval>(DateInterval { Sunday, 01 March 2026, Monday, 02 March 2026, Tuesday, 03 March 2026, Wednesday, 04 March 2026, Thursday, 05 March 2026, Friday, 06
       March 2026, Saturday, 07 March 2026, Sunday, 08 March 2026, Monday, 09 March 2026, Tuesday, 10 March 2026, Wednesday, 11 March 2026, Thursday, 12 March 2026, Friday, 13 March 20
      26, Saturday, 14 March 2026, Sunday, 15 March 2026, Monday, 16 March 2026, Tuesday, 17 March 2026, Wednesday, 18 March 2026, Thursday, 19 March 2026, Friday, 20 March 2026, Satur
      day, 21 March 2026, Sunday, 22 March 2026, Monday, 23 March 2026, Tuesday, 24 March 2026, Wednesday, 25 March 2026, Thursday, 26 March 2026, Friday, 27 March 2026, Saturday, 28 M
      arch 2026, Sunday, 29 March 2026, Monday, 30 March 2026, Tuesday, 31 March 2026 }), 
      	e: d.Template.ValidFrom)
      Stack Trace:
         at LinqToDB.Internal.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in /_/Source/LinqToDB/Internal/Linq/Builder/ExpressionBuilder.cs:line 376
         at LinqToDB.Internal.Linq.Builder.ExpressionBuilder.Build[T](IQueryExpressions& expressions) in /_/Source/LinqToDB/Internal/Linq/Builder/ExpressionBuilder.cs:line 128
         at LinqToDB.Internal.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, IQueryExpre
      ssions& expressions) in /_/Source/LinqToDB/Internal/Linq/Query{T}.cs:line 403
         at LinqToDB.Internal.Linq.Query`1.GetQuery(IDataContext dataContext, IQueryExpressions& expressions, Boolean& dependsOnParameters) in /_/Source/LinqToDB/Internal/Linq/Query{T}
      .cs:line 380
         at LinqToDB.Internal.Linq.ExpressionQuery`1.GetQuery(IQueryExpressions& expression, Boolean cache, Boolean& dependsOnParameters) in /_/Source/LinqToDB/Internal/Linq/Expression
      Query.cs:line 91
         at LinqToDB.Internal.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression) in /_/Source/LinqToDB/Internal/Linq/ExpressionQuery.cs:line 312
         at LinqToDbQuery10_0_201.TestWindow() in /src/UnitTest1.fs:line 106
         at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
         at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)

Test summary: total: 2, failed: 1, succeeded: 1, skipped: 0, duration: 1.8s
Build failed with 1 error(s) in 5.2s
```

### Regression?

It worked with SDK 10.0.103 as shown in minimal reproduction repro.

### Linq To DB version

6.2.0

### .NET version

10.0.201

### Database

PostgreSQL

### Database provider

Npgsql 10.0.2

### Operating system

Linux

**Comment by MaceWindu** [comment]
10.0.4 release was a big "success", I'm not surprised TBH

**Comment by MaceWindu** [comment]
Try to reference FSharp.Core directly using 10.0.105  or 10.0.104 version as workaround.

**Comment by gubser** [comment]
Thanks! I tried it with 10.0.105 and it works: https://github.com/gubser/linq2db-window-query/commit/a0024c52d4c5c5e03e75b80219c42891bc3037b0

**Comment by MaceWindu** [comment]
F# de-optimized generated expression in unexpected way. We will try to handle such generation

**Comment by MaceWindu** [comment]
Looks like they fixed long-standing issue with silently converting queryable to enumerable which lead to client-side evaluation

**Comment by gubser** [comment]
Nice. You mean [this one](https://github.com/dotnet/fsharp/pull/19243)?

**Comment by MaceWindu** [comment]
Probably, at least fix `Use Queryable.Select instead of Enumerable.Select + AsQueryable` sounds like it

**Comment by MaceWindu** [comment]
I wonder why they mention EFCore when EFCore.FSharp had no updates for ages and doesn't work with modern EFCore versions
